/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClothesNGORole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ClothesNGOOrganization;
import Business.Organization.Organization;
import Business.Organization.WarehouseCollectionOrganization;
import Business.SendEmail.SendEmail;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AcceptDonationWorkRequest;
import Business.WorkQueue.CollectDonationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepankkhurana
 */
public class ClothesNGORoleWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ClothesNGORoleWorkArea
     */
    private final JPanel userProcessContainer;
    private final ClothesNGOOrganization organization;
    private final Enterprise enterprise;
    private final UserAccount userAccount;
    private final ArrayList<Organization> orgs;
    private final EcoSystem system;
    private final Network network;

    public ClothesNGORoleWorkArea(JPanel userProcessContainer, UserAccount account, ClothesNGOOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.network = network;
        this.orgs = new ArrayList<>();
        try {
            valueLabel.setText(organization.getName());
            networkLbl.setText(network.getName());

            String imageFilePath = "./Donate.jpg";
            ImageIcon icon = new ImageIcon(imageFilePath);
            Image image = icon.getImage().getScaledInstance(1450, 900, Image.SCALE_SMOOTH);
            backgroundLbl.setIcon(new ImageIcon(image));

            for (Network n : system.getNetworkList()) {
                if (n.getName().equals(network.getName())) {
                    for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            orgs.add(o);
                        }
                    }
                }
            }
            btnSend.setEnabled(false);
            populateRequestTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }

    public void populateRequestTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

            model.setRowCount(0);
            for (Organization org : orgs) {
                if (org instanceof ClothesNGOOrganization) {
                    for (AcceptDonationWorkRequest request : org.getWorkQueue().getDonationWorkRequestList()) {
                        if (request.getDonor().getNetwork().equals(network.getName())) {
                            Object[] row = new Object[5];
                            row[0] = request;
                            row[1] = request.getDonor().getEmailid();
                            row[2] = request.getDonor().getContactNumber();
                            row[3] = request.getDonor().getAddress();
                            row[4] = request.getSender() == null ? null : request.getSender().getEmployee().getName();
                            model.addRow(row);
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnTrack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 140, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donations Received at");

        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<EnterpriseName>");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Network");

        networkLbl.setForeground(new java.awt.Color(255, 255, 255));
        networkLbl.setText("<NetworkName>");

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email Id", "Contact Number", "Address", "Approved By"
            }
        ));
        jScrollPane1.setViewportView(workRequestJTable);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Approve Donation");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Send request to collection warehouse");

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Track previously sent collection request or Place new distribution request");

        btnTrack.setText("Track");
        btnTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Donation Details :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(valueLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(264, 264, 264)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(537, 537, 537)
                .addComponent(btnApprove))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(networkLbl))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(537, 537, 537)
                .addComponent(btnTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnSend)))
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(btnApprove))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(networkLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(603, 603, 603)
                .addComponent(btnTrack))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a donation to approve.");
            return;
        }
        try {
            String approvedBy = String.valueOf(workRequestJTable.getValueAt(selectedRow, 4));
            if (approvedBy.equals("null")) {
                WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
                AcceptDonationWorkRequest req = (AcceptDonationWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
                request.setSender(userAccount);
                request.setStatus("Pending");
                populateRequestTable();

                //Send Email to donor
                String to = req.getDonor().getEmailid();
                String subject = "Donation accepted!";
                String message = "Thank you! Your donation is accepted. You will be notified of your pickup details within 24 hours.";

                String user = "aeddemogss@gmail.com";
                String pass = "aed_gss123";

                SendEmail.send(to, subject, message, user, pass);
                btnSend.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Already approved.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a donation to send for collection.");
            return;
        }
        try {
            String approvedBy = String.valueOf(workRequestJTable.getValueAt(selectedRow, 4));
            AcceptDonationWorkRequest request = (AcceptDonationWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            for (Organization o : orgs) {
                if (o instanceof WarehouseCollectionOrganization && approvedBy.equals(userAccount.getEmployee().getName())) {
                    CollectDonationWorkRequest collectionRequest = new CollectDonationWorkRequest();
                    collectionRequest.setDonorName(String.valueOf(workRequestJTable.getValueAt(selectedRow, 0)));
                    collectionRequest.setDonorContactNumber(String.valueOf(workRequestJTable.getValueAt(selectedRow, 2)));
                    collectionRequest.setDonorAddress(String.valueOf(workRequestJTable.getValueAt(selectedRow, 3)));
                    collectionRequest.setRequestedBy(String.valueOf(workRequestJTable.getValueAt(selectedRow, 4)));
                    collectionRequest.setStatus("Sent");
                    collectionRequest.setDonationType(request.getDonor().getDonationType());
                    collectionRequest.setDonorEmailId(request.getDonor().getEmailid());
                    o.getWorkQueue().getCollectionWorkRequestList().add(collectionRequest);
                    JOptionPane.showMessageDialog(null, "Collection request sent to Collection Warehouse.");
                    break;
                }
            }
            btnSend.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackActionPerformed
        try {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            for (Organization o : orgs) {
                if (o instanceof WarehouseCollectionOrganization) {
                    userProcessContainer.add("TrackRequestStatusJPanel", new TrackRequestStatusJPanel(userProcessContainer, userAccount, enterprise, o.getWorkQueue().getCollectionWorkRequestList(), system));
                    layout.next(userProcessContainer);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnTrackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnTrack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel networkLbl;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
