/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseCollectionRole;

import Business.EcoSystem;
import Business.Inventory.InventoryDetails;
import Business.Inventory.InventoryDirectory;
import Business.Organization.WarehouseCollectionOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CollectDonationWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepankkhurana
 */
public class UpdateCollectionRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCollectionRequestJPanel
     */
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final CollectDonationWorkRequest request;
    private final EcoSystem system;
    private final WarehouseCollectionOrganization organization;
    private final InventoryDirectory inventoryDirectory;
    
    public UpdateCollectionRequestJPanel(JPanel userProcessContainer, UserAccount account, WarehouseCollectionOrganization organization, CollectDonationWorkRequest request, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.request = request;
        this.system = system;
        this.organization = organization;
        if (organization.getInventoryDirectory() == null){
            this.inventoryDirectory = new InventoryDirectory();
        }
        else {
            this.inventoryDirectory = organization.getInventoryDirectory();
            
            populateInventoryListJTable();
        }
        try{
        
        donationTypeTxtBox.setEnabled(false);
        donationIdTxtBox.setEnabled(false);;
        descTxtBox.setEnabled(false);
        quantityTxtBox.setEnabled(false);
        btnAdd.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    
    public void populateInventoryListJTable(){
        try{
        DefaultTableModel model = (DefaultTableModel)inventoryListJTable.getModel();
        model.setRowCount(0);
        for(InventoryDetails inventory : inventoryDirectory.getInventory()){
            Object[] row = new Object[4];
            row[0] = inventory.getDonationId();
            row[1] = inventory.getDonationType();
            row[2] = inventory.getDescription();
            row[3] = inventory.getQuantity();
            model.addRow(row);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryListJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        donationTypeTxtBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantityTxtBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTxtBox = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        donationIdTxtBox = new javax.swing.JTextField();
        backgroundLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 140, 190));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Is donation item collected?");

        btnYes.setText("Yes");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        inventoryListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Donation Id", "Donation Type", "Description", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(inventoryListJTable);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Inventory Details Below : ");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Donation Type");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description*");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity*");

        descTxtBox.setColumns(20);
        descTxtBox.setRows(5);
        jScrollPane2.setViewportView(descTxtBox);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Donation Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(btnYes))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(466, 466, 466)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(donationIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(quantityTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(btnAdd))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(donationTypeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnYes)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel6)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel4)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(donationIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(quantityTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(btnAdd))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(642, 642, 642)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(donationTypeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        try{
        request.setStatus("Complete");
        descTxtBox.setEnabled(true);
        quantityTxtBox.setEnabled(true);
        donationTypeTxtBox.setText(request.getDonationType());
        donationIdTxtBox.setText(String.valueOf(request.getDonationId()));
        btnYes.setEnabled(false);
        btnAdd.setEnabled(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try{
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WarehouseCollectionRoleWorkArea jp = (WarehouseCollectionRoleWorkArea)component;
        jp.populateCollectionRequestJTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int donationId = Integer.parseInt(donationIdTxtBox.getText());
        String donationType = donationTypeTxtBox.getText();
        String desc = descTxtBox.getText();
        try{
            int quantity = Integer.parseInt(quantityTxtBox.getText());
            if(!donationType.isEmpty() && !desc.isEmpty() && !quantityTxtBox.getText().isEmpty()){
                inventoryDirectory.createInventory(donationId,donationType, desc, quantity);
                JOptionPane.showMessageDialog(null,"Inventory Updated");
                populateInventoryListJTable();
                btnAdd.setEnabled(false);
            }
            else JOptionPane.showMessageDialog(null,"Fields marked with * are compulsory.");
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please input value of quantity in whole numbers");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnYes;
    private javax.swing.JTextArea descTxtBox;
    private javax.swing.JTextField donationIdTxtBox;
    private javax.swing.JTextField donationTypeTxtBox;
    private javax.swing.JTable inventoryListJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField quantityTxtBox;
    // End of variables declaration//GEN-END:variables
}
