/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistantRole;

import Business.SendEmail.SendEmail;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author deepankkhurana
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final LabWorkRequest request;
    
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, LabWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.request = request;
        try{
        testResultComboBox.removeAllItems();
        testResultComboBox.addItem("Optimal");
        testResultComboBox.addItem("Not Optimal");
        testTypelbl.setText(request.getTestType());
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnComplete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        testTypelbl = new javax.swing.JLabel();
        optimumRangeDefinition = new javax.swing.JLabel();
        testResultComboBox = new javax.swing.JComboBox();
        backgroundLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 140, 190));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Test Result");

        BtnComplete.setText("Complete");
        BtnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCompleteActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Test Type");

        testTypelbl.setForeground(new java.awt.Color(255, 255, 255));
        testTypelbl.setText("<Test Type>");

        optimumRangeDefinition.setForeground(new java.awt.Color(255, 255, 255));
        optimumRangeDefinition.setText("<html><p>Optimal result for Blood Test: <br>1. Verified blood group <br>2. Heamoglobin Range : 12-16 grams per deciliter <br> <br>Optimal result for Organ Test: <br>1. Kidney - Healthy <br>2. Eye - Healthy </p> </html>");

        testResultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(testTypelbl))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(BtnComplete))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(testResultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(optimumRangeDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(testTypelbl))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(BtnComplete))
            .addGroup(layout.createSequentialGroup()
                .addGap(595, 595, 595)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(testResultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(optimumRangeDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCompleteActionPerformed
        try{
        WorkRequest r = (WorkRequest)request;
        r.setMessage(String.valueOf(testResultComboBox.getSelectedItem()));
        r.setStatus("Complete");
        JOptionPane.showMessageDialog(null, "Completed successfully.");
        
        //Send Email to donor
        String message="";
        String to = request.getDonorEmailId();
        String subject = "Donation verdict";
        switch (String.valueOf(testResultComboBox.getSelectedItem())) {
            case "Optimal":
                message =  "Thank you! Your donation is accepted. We appreciate you endeavor to support a needy!";
                break;
            case "Not Optimal":
                message =  "We appreciate you endeavor to support a needy. We are sorry, but we found that your donation doesn't meet the required medical conditions to be optimal. Please reach out to us again in near future.";
                break;
        }
        String user = "aeddemogss@gmail.com";
        String pass = "aed_gss123";

        SendEmail.send(to,subject, message, user, pass);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_BtnCompleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try{
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabAssistantWorkAreaJPanel jp = (LabAssistantWorkAreaJPanel)component;
        jp.populateWorkRequestJTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnComplete;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel optimumRangeDefinition;
    private javax.swing.JComboBox testResultComboBox;
    private javax.swing.JLabel testTypelbl;
    // End of variables declaration//GEN-END:variables
}
