/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodNGORole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.WarehouseDistributionOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CollectDonationWorkRequest;
import Business.WorkQueue.DistributeDonationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepankkhurana
 */
public class TrackRequestStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrackRequestStatus
     */
    private final JPanel userProcessContainer;
    private final Enterprise enterprise;
    private UserAccount userAccount;
    private final ArrayList<CollectDonationWorkRequest> collectionWorkRequestList;
    private final EcoSystem system;
    
    public TrackRequestStatusJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, ArrayList<CollectDonationWorkRequest> collectionWorkRequestList, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.collectionWorkRequestList = collectionWorkRequestList;
        this.system = system;
        try{
        populateTrackStatusJTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    
    public void populateTrackStatusJTable(){
        try{
        DefaultTableModel model = (DefaultTableModel) trackStatusJTable.getModel();
        model.setRowCount(0);
        for(CollectDonationWorkRequest request : collectionWorkRequestList){
            if(request.getDonationType().equals("Food")){
               Object[] row = new Object[4];
               row[0] = request;
               row[1] = request.getRequestedBy();
               row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
               row[3] = request.getStatus();
               model.addRow(row); 
            }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trackStatusJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTrackDistribution = new javax.swing.JButton();
        locationTxtBox = new javax.swing.JTextField();
        backgroundLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 140, 190));

        trackStatusJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Donor Name", "Request Sent By", "Request Received By", "Status"
            }
        ));
        jScrollPane1.setViewportView(trackStatusJTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Track previously sent Collection Requests below : ");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Place distribution request at location");

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><p>Status key: <br> <br> Sent - Donation sent for collection <br> <br> Complete - Donation is picked up and stored in Collection Warehouse <br> <br> Distribution Requested - Distribution request is placed at Distribution Warehouse <br> <br> Distributed - Donation is distributed </p> </html>");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Track previously sent distribution request");

        btnTrackDistribution.setText("Track");
        btnTrackDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackDistributionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(btnRequest))
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(btnTrackDistribution, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(1047, 1047, 1047)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(locationTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(btnRequest))
            .addGroup(layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addComponent(btnTrackDistribution))
            .addGroup(layout.createSequentialGroup()
                .addGap(638, 638, 638)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(locationTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try{
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FoodNGORoleWorkArea jp = (FoodNGORoleWorkArea)component;
        jp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        int selectedRow = trackStatusJTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a request.");
        }
        try{
        String status = String.valueOf(trackStatusJTable.getValueAt(selectedRow, 3));
        if(status.equals("Complete")){
            CollectDonationWorkRequest request = (CollectDonationWorkRequest)trackStatusJTable.getValueAt(selectedRow, 0);
            WorkRequest workRequest = (WorkRequest)trackStatusJTable.getValueAt(selectedRow, 0);
            if(!locationTxtBox.getText().isEmpty()){
                DistributeDonationWorkRequest donationRequest = new DistributeDonationWorkRequest();
                donationRequest.setDonationId(request.getDonationId());
                donationRequest.setDonationType(request.getDonationType());
                donationRequest.setSender(userAccount);
                donationRequest.setLocation(locationTxtBox.getText());
                for(Network n : system.getNetworkList()){
                    for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                        for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                            if(o instanceof WarehouseDistributionOrganization){
                                o.getWorkQueue().getDistributionWorkRequestList().add(donationRequest);
                                workRequest.setStatus("Distribution Requested");
                                populateTrackStatusJTable();
                                JOptionPane.showMessageDialog(null, "Request sent to Warehouse Distribution.");
                                break;
                            }
                        }
                    }
                }
            }
            else JOptionPane.showMessageDialog(null, "Please provide location of distribution.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a completed request.");
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnTrackDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackDistributionActionPerformed
        try{
        for(Network n : system.getNetworkList()){
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof WarehouseDistributionOrganization){
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("TrackDistributionRequestJPanel",new TrackDistributionRequestJPanel(userProcessContainer,userAccount,enterprise,o.getWorkQueue().getDistributionWorkRequestList()));
                        layout.next(userProcessContainer);
                        break;
                    }
                }
            }
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }//GEN-LAST:event_btnTrackDistributionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnTrackDistribution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locationTxtBox;
    private javax.swing.JTable trackStatusJTable;
    // End of variables declaration//GEN-END:variables
}
