/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodNGORole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DistributeDonationWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deepankkhurana
 */
public class TrackDistributionRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrackDistributionRequestJPanel
     */
    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final Enterprise enterprise;
    private final ArrayList<DistributeDonationWorkRequest> distributionWorkRequestList;
    
    public TrackDistributionRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, ArrayList<DistributeDonationWorkRequest> distributionWorkRequestList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.distributionWorkRequestList = distributionWorkRequestList;
        try{
        String imageFilePath = "./Donate.jpg";
        ImageIcon icon=new ImageIcon(imageFilePath);
        Image image = icon.getImage().getScaledInstance(1450, 900, Image.SCALE_SMOOTH);
        backgroundLbl.setIcon(new ImageIcon(image));
        populateDistributionWorkRequestJTable();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
        
    }
    
    public void populateDistributionWorkRequestJTable(){
        try{
        DefaultTableModel model = (DefaultTableModel) distributionWorkRequestJTable.getModel();
        model.setRowCount(0);
        for(DistributeDonationWorkRequest request : distributionWorkRequestList){
           Object[] row = new Object[5];
           row[0] = request;
           row[1] = request.getSender() == null ? null : request.getSender().getEmployee().getName();
           row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
           row[3] = request.getLocation();
           row[4] = request.getStatus();
           model.addRow(row); 
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong..");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        distributionWorkRequestJTable = new javax.swing.JTable();
        backgroundLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 140, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Track previously sent Distribution Requests here : ");

        distributionWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Donation Type", "Requested by", "Accepted By", "Location", "Status"
            }
        ));
        jScrollPane1.setViewportView(distributionWorkRequestJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JTable distributionWorkRequestJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
